version: '3.8'

services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rms
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"  

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
